# Generated by Django 6.1.1 on 2026-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorderitem_item_total_salesorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
