# Generated by Django 6.1.1 on 2026-09-11 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=50, unique=True)),
                ('po_id', models.IntegerField()),
                ('warehouse_id', models.IntegerField()),
                ('status', models.CharField(default='DRAFT', max_length=30)),
            ],
            options={
                'db_table': 'grns',
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('serial_id', models.IntegerField(blank=True, null=True)),
                ('grn_id', models.ForeignKey(db_column='grn_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.grn')),
            ],
            options={
                'db_table': 'grn_items',
            },
        ),
    ]
