# Generated by Django 6.1.1 on 2026-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_temporaryproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=50, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
            options={
                'db_table': 'temporary_suppliers',
            },
        ),
    ]
