# Generated by Django 6.1.1 on 2026-09-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_temporarysupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
