# Generated by Django 6.1.1 on 2026-09-21 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0004_grn_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grn',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='receiving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
