# Generated by Django 6.1.1 on 2026-09-23 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RESERVE', 'Reservation'), ('RELEASE', 'Reservation Release'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.PositiveBigIntegerField()),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'db_table': 'inventorytransaction',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('stock_balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_quantity', models.PositiveBigIntegerField(default=0)),
                ('reserved_quantity', models.PositiveBigIntegerField(default=0)),
                ('available_quantity', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Warehouse.warehouse')),
            ],
            options={
                'db_table': 'stockbalance',
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse', 'location'), name='unique_product_warehouse_location_stock')],
            },
        ),
    ]
