# Generated by Django 6.1.1 on 2026-09-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='adjustment_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
